# Generated by Django 5.1.7 on 2026-05-03 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LDAPSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="LDAP Principal", max_length=100, unique=True
                    ),
                ),
                ("is_enabled", models.BooleanField(default=False)),
                (
                    "server_uri",
                    models.CharField(
                        help_text="Ej: ldap://ldap.midominio.local:389", max_length=255
                    ),
                ),
                ("use_ssl", models.BooleanField(default=False)),
                ("bind_dn", models.CharField(blank=True, max_length=255)),
                ("bind_password", models.CharField(blank=True, max_length=255)),
                ("user_search_base", models.CharField(blank=True, max_length=255)),
                (
                    "user_search_filter",
                    models.CharField(
                        default="(sAMAccountName={username})",
                        help_text="Filtro LDAP. Placeholder disponible: {username}",
                        max_length=255,
                    ),
                ),
                (
                    "user_dn_template",
                    models.CharField(
                        blank=True,
                        help_text="Opcional. Ej: uid={username},ou=users,dc=example,dc=com",
                        max_length=255,
                    ),
                ),
                (
                    "first_name_attr",
                    models.CharField(default="givenName", max_length=100),
                ),
                ("last_name_attr", models.CharField(default="sn", max_length=100)),
                ("email_attr", models.CharField(default="mail", max_length=100)),
                (
                    "display_name_attr",
                    models.CharField(default="displayName", max_length=100),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configuración LDAP",
                "verbose_name_plural": "Configuraciones LDAP",
            },
        ),
    ]
