# Generated by Django 6.0.5 on 2026-06-24 14:00

import base64
import hashlib

from cryptography.fernet import Fernet
from django.conf import settings
from django.db import migrations, models


LDAP_SECRET_PREFIX = "fernet$"


def encrypt_existing_bind_passwords(apps, schema_editor):
    LDAPSettings = apps.get_model("accounts", "LDAPSettings")
    raw_key = getattr(settings, "LDAP_SECRET_KEY", "") or settings.SECRET_KEY
    digest = hashlib.sha256(str(raw_key).encode("utf-8")).digest()
    fernet = Fernet(base64.urlsafe_b64encode(digest))
    for config in LDAPSettings.objects.exclude(bind_password=""):
        if config.bind_password.startswith(LDAP_SECRET_PREFIX):
            continue
        config.bind_password = LDAP_SECRET_PREFIX + fernet.encrypt(config.bind_password.encode("utf-8")).decode("ascii")
        config.save(update_fields=["bind_password"])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_ldapsettings_auth_mode_ldapauthlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ldapsettings',
            name='bind_password',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.RunPython(encrypt_existing_bind_passwords, migrations.RunPython.noop),
    ]
