# Generated by Django 6.0.5 on 2026-06-21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("usecases", "0025_alter_mitreattacksyncsettings_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name="MitreAttack",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("external_id", models.CharField(max_length=20, unique=True, verbose_name="ID ATT&CK")),
                        ("name", models.CharField(max_length=255, verbose_name="Nombre")),
                        ("tactic", models.CharField(blank=True, max_length=100, verbose_name="TÃ¡ctica")),
                        ("is_enabled", models.BooleanField(default=True, verbose_name="Habilitada")),
                        ("disabled_reason", models.TextField(blank=True, default="", help_text="Explica por quÃ© esta tÃ©cnica ATT&CK fue deshabilitada.", verbose_name="Motivo de deshabilitaciÃ³n")),
                        ("notes", models.TextField(blank=True, default="", help_text="Notas internas sobre la tÃ©cnica ATT&CK o su aplicabilidad en el SOC.", verbose_name="Notas internas")),
                    ],
                    options={
                        "verbose_name": "MITRE ATT&CK",
                        "verbose_name_plural": "MITRE ATT&CK",
                        "db_table": "usecases_mitreattack",
                        "ordering": ["external_id"],
                    },
                ),
                migrations.CreateModel(
                    name="D3Fend",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("code", models.CharField(max_length=120, unique=True, verbose_name="CÃ³digo D3FEND")),
                        ("name", models.CharField(blank=True, max_length=255, verbose_name="Nombre")),
                        ("category", models.CharField(blank=True, max_length=100, verbose_name="CategorÃ­a")),
                        ("is_enabled", models.BooleanField(default=True, verbose_name="Habilitada")),
                        ("description", models.TextField(blank=True, default="", help_text="DescripciÃ³n de la tÃ©cnica D3FEND.", verbose_name="DescripciÃ³n")),
                        ("disabled_reason", models.TextField(blank=True, default="", help_text="Explica por quÃ© esta tÃ©cnica D3FEND fue deshabilitada.", verbose_name="Motivo de deshabilitaciÃ³n")),
                        ("notes", models.TextField(blank=True, default="", help_text="Notas internas sobre la tÃ©cnica D3FEND o su aplicabilidad en el SOC.", verbose_name="Notas internas")),
                        ("related_attacks", models.ManyToManyField(blank=True, db_table="usecases_d3fend_related_attacks", help_text="RelaciÃ³n inferida por D3FEND entre esta tÃ©cnica defensiva y tÃ©cnicas ATT&CK.", related_name="related_d3fends", to="mitre.mitreattack", verbose_name="ATT&CK relacionados por D3FEND")),
                    ],
                    options={
                        "verbose_name": "D3FEND",
                        "verbose_name_plural": "D3FEND",
                        "db_table": "usecases_d3fend",
                        "ordering": ["code"],
                    },
                ),
                migrations.CreateModel(
                    name="MitreAttackSyncSettings",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("is_active", models.BooleanField(default=True)),
                        ("name", models.CharField(default="Sincronizacion MITRE principal", max_length=100, unique=True)),
                        ("interval_value", models.PositiveIntegerField(default=24, verbose_name="Intervalo")),
                        ("interval_unit", models.CharField(choices=[("hours", "Horas"), ("days", "Dias")], default="hours", max_length=10, verbose_name="Unidad")),
                        ("last_run_at", models.DateTimeField(blank=True, null=True, verbose_name="Ultima ejecucion")),
                        ("last_success_at", models.DateTimeField(blank=True, null=True, verbose_name="Ultima ejecucion OK")),
                        ("last_status", models.CharField(choices=[("never", "Nunca ejecutado"), ("running", "En ejecucion"), ("success", "OK"), ("error", "Error")], default="never", max_length=20, verbose_name="Ultimo estado")),
                        ("last_message", models.TextField(blank=True, default="", verbose_name="Ultimo mensaje")),
                        ("last_created", models.PositiveIntegerField(default=0, verbose_name="Ultimos creados")),
                        ("last_updated", models.PositiveIntegerField(default=0, verbose_name="Ultimos actualizados")),
                        ("last_skipped", models.PositiveIntegerField(default=0, verbose_name="Ultimos omitidos")),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                    ],
                    options={
                        "verbose_name": "Sincronizacion de frameworks",
                        "verbose_name_plural": "Sincronizaciones de frameworks",
                        "db_table": "usecases_mitreattacksyncsettings",
                        "constraints": [
                            models.UniqueConstraint(condition=models.Q(("is_active", True)), fields=("is_active",), name="unique_active_mitre_attack_sync_settings"),
                        ],
                    },
                ),
                migrations.CreateModel(
                    name="CoverageOverride",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("framework", models.CharField(choices=[("ATTACK", "ATT&CK"), ("D3FEND", "D3FEND")], max_length=12, verbose_name="Framework")),
                        ("object_type", models.CharField(choices=[("tactic", "TÃ¡ctica ATT&CK"), ("technique", "TÃ©cnica"), ("category", "CategorÃ­a D3FEND")], max_length=20, verbose_name="Tipo de objeto")),
                        ("object_key", models.CharField(max_length=160, verbose_name="Clave")),
                        ("object_name", models.CharField(blank=True, default="", max_length=255, verbose_name="Nombre")),
                        ("status", models.CharField(choices=[("enabled", "Habilitada"), ("fulfilled", "Cumplida por herramienta"), ("disabled", "Deshabilitada / no aplica")], default="enabled", max_length=20, verbose_name="Estado")),
                        ("reason", models.TextField(blank=True, default="", help_text="Obligatorio si se marca como cumplida por herramienta o deshabilitada/no aplica.", verbose_name="Motivo / evidencia")),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="coverage_overrides_updated", to=settings.AUTH_USER_MODEL, verbose_name="Actualizado por")),
                    ],
                    options={
                        "verbose_name": "Override de cobertura",
                        "verbose_name_plural": "Overrides de cobertura",
                        "db_table": "usecases_coverageoverride",
                        "ordering": ["framework", "object_type", "object_key"],
                        "constraints": [
                            models.UniqueConstraint(fields=("framework", "object_type", "object_key"), name="unique_coverage_override_target"),
                        ],
                    },
                ),
            ],
        ),
    ]
