# Generated by Django 6.0.5 on 2026-06-25 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitre', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverageoverride',
            name='object_type',
            field=models.CharField(choices=[('tactic', 'Táctica ATT&CK'), ('technique', 'Técnica'), ('category', 'Categoría D3FEND')], max_length=20, verbose_name='Tipo de objeto'),
        ),
        migrations.AlterField(
            model_name='d3fend',
            name='category',
            field=models.CharField(blank=True, max_length=100, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='d3fend',
            name='code',
            field=models.CharField(max_length=120, unique=True, verbose_name='Código D3FEND'),
        ),
        migrations.AlterField(
            model_name='d3fend',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Descripción de la técnica D3FEND.', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='d3fend',
            name='disabled_reason',
            field=models.TextField(blank=True, default='', help_text='Explica por qué esta técnica D3FEND fue deshabilitada.', verbose_name='Motivo de deshabilitación'),
        ),
        migrations.AlterField(
            model_name='d3fend',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Notas internas sobre la técnica D3FEND o su aplicabilidad en el SOC.', verbose_name='Notas internas'),
        ),
        migrations.AlterField(
            model_name='d3fend',
            name='related_attacks',
            field=models.ManyToManyField(blank=True, db_table='usecases_d3fend_related_attacks', help_text='Relación inferida por D3FEND entre esta técnica defensiva y técnicas ATT&CK.', related_name='related_d3fends', to='mitre.mitreattack', verbose_name='ATT&CK relacionados por D3FEND'),
        ),
        migrations.AlterField(
            model_name='mitreattack',
            name='disabled_reason',
            field=models.TextField(blank=True, default='', help_text='Explica por qué esta técnica ATT&CK fue deshabilitada.', verbose_name='Motivo de deshabilitación'),
        ),
        migrations.AlterField(
            model_name='mitreattack',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Notas internas sobre la técnica ATT&CK o su aplicabilidad en el SOC.', verbose_name='Notas internas'),
        ),
        migrations.AlterField(
            model_name='mitreattack',
            name='tactic',
            field=models.CharField(blank=True, max_length=100, verbose_name='Táctica'),
        ),
    ]
