# Generated by Django 6.0.5 on 2026-06-25 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitre', '0002_alter_coverageoverride_object_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mitreattacksyncsettings',
            name='last_run_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última ejecución'),
        ),
        migrations.AlterField(
            model_name='mitreattacksyncsettings',
            name='last_success_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última ejecución OK'),
        ),
    ]
