# Generated by Django 5.2.15 on 2026-07-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitre', '0004_d3fendattackrelationoverride'),
    ]

    operations = [
        migrations.AddField(
            model_name='mitreattacksyncsettings',
            name='d3fend_catalog_base_url',
            field=models.URLField(blank=True, default='https://d3fend.mitre.org/ontologies/d3fend/', help_text='Indice oficial donde MITRE publica las versiones del catalogo D3FEND.', max_length=500, verbose_name='URL base catalogo D3FEND'),
        ),
        migrations.AddField(
            model_name='mitreattacksyncsettings',
            name='d3fend_catalog_url',
            field=models.URLField(blank=True, default='', help_text='Opcional. Si se completa, se usa esta URL exacta y no se resuelve version.', max_length=500, verbose_name='URL CSV catalogo D3FEND'),
        ),
        migrations.AddField(
            model_name='mitreattacksyncsettings',
            name='d3fend_catalog_version',
            field=models.CharField(blank=True, default='latest', help_text="Usa 'latest' para resolver automaticamente la ultima version publicada.", max_length=40, verbose_name='Version catalogo D3FEND'),
        ),
    ]
