# Generated by Django 6.0.5 on 2026-06-23 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('executive', 'Ejecutivo'), ('mitre', 'MITRE / D3FEND'), ('inventory', 'Inventario'), ('lifecycle', 'Ciclo de vida'), ('controls', 'Controles')], max_length=32)),
                ('filename', models.CharField(max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_downloads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Descarga de reporte',
                'verbose_name_plural': 'Descargas de reportes',
                'ordering': ['-created_at', '-id'],
                'permissions': [('export_reports', 'Can export reports')],
            },
        ),
    ]
