# Generated by Django 6.0.5 on 2026-06-24 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplateConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('executive', 'Ejecutivo'), ('mitre', 'MITRE / D3FEND'), ('inventory', 'Inventario'), ('lifecycle', 'Ciclo de vida'), ('controls', 'Controles')], max_length=32, unique=True)),
                ('organization_name', models.CharField(default='SOC Control Manager', max_length=180)),
                ('document_label', models.CharField(default='Gobierno de Seguridad', max_length=180)),
                ('report_title', models.CharField(blank=True, max_length=220)),
                ('introduction_text', models.TextField(blank=True, default='Inventario y trazabilidad operativa')),
                ('primary_color', models.CharField(default='#1d4ed8', max_length=7)),
                ('accent_color', models.CharField(default='#22c55e', max_length=7)),
                ('footer_text', models.CharField(default='Documento generado por SOC Control Manager', max_length=255)),
                ('confidentiality_label', models.CharField(default='Uso interno', max_length=120)),
                ('logo', models.FileField(blank=True, null=True, upload_to='reporting/')),
                ('sections', models.JSONField(blank=True, default=list)),
                ('show_header', models.BooleanField(default=True)),
                ('show_footer', models.BooleanField(default=True)),
                ('show_generation_date', models.BooleanField(default=True)),
                ('show_page_numbers', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_report_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plantilla de reporte',
                'verbose_name_plural': 'Plantillas de reportes',
                'ordering': ['report_type'],
                'permissions': [('configure_report_templates', 'Can configure report templates')],
            },
        ),
    ]
