# Generated by Django 6.0.5 on 2026-06-21

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("usecases", "0025_alter_mitreattacksyncsettings_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name="LifecycleReview",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("status", models.CharField(default="Finalizado", max_length=20, verbose_name="Estado")),
                        ("result", models.CharField(blank=True, default="", max_length=20, verbose_name="Resultado")),
                        ("notes", models.TextField(blank=True, verbose_name="Notas")),
                        ("checked_at", models.DateField(default=datetime.date.today, verbose_name="Fecha control")),
                        ("next_review_date", models.DateField(blank=True, null=True, verbose_name="PrÃ³ximo control")),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("completed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="lifecycle_reviews_completed", to=settings.AUTH_USER_MODEL, verbose_name="Finalizado por")),
                        ("control_owner", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="lifecycle_reviews_owned", to=settings.AUTH_USER_MODEL, verbose_name="Responsable control")),
                        ("use_case", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="lifecycle_reviews", to="usecases.usecase", verbose_name="Caso de uso")),
                    ],
                    options={
                        "verbose_name": "Historial de revisiÃ³n",
                        "verbose_name_plural": "Historial de revisiones",
                        "db_table": "usecases_lifecyclereview",
                        "ordering": ["-checked_at", "-created_at"],
                    },
                ),
                migrations.CreateModel(
                    name="LifecycleSettings",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("is_active", models.BooleanField(default=True)),
                        ("name", models.CharField(default="PolÃ­tica principal", max_length=100, unique=True)),
                        ("review_interval_days", models.PositiveIntegerField(default=120, verbose_name="DÃ­as entre controles")),
                    ],
                    options={
                        "verbose_name": "ConfiguraciÃ³n ciclo de vida",
                        "verbose_name_plural": "Configuraciones ciclo de vida",
                        "db_table": "usecases_lifecyclesettings",
                        "constraints": [
                            models.UniqueConstraint(condition=models.Q(("is_active", True)), fields=("is_active",), name="unique_active_lifecycle_settings"),
                        ],
                    },
                ),
            ],
        ),
    ]
