# Generated by Django 6.0.5 on 2026-06-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifecycle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifecyclereview',
            name='alert_triggered_90d',
            field=models.BooleanField(default=False, verbose_name='Alerto en el periodo'),
        ),
        migrations.AddField(
            model_name='lifecyclereview',
            name='event_ids_valid',
            field=models.BooleanField(default=True, verbose_name='Event IDs vigentes'),
        ),
        migrations.AddField(
            model_name='lifecyclereview',
            name='false_positives',
            field=models.PositiveIntegerField(default=0, verbose_name='Falsos positivos'),
        ),
        migrations.AddField(
            model_name='lifecyclereview',
            name='fields_exist',
            field=models.BooleanField(default=True, verbose_name='Campos existentes'),
        ),
        migrations.AddField(
            model_name='lifecyclereview',
            name='logic_valid',
            field=models.BooleanField(default=True, verbose_name='Logica funcional'),
        ),
        migrations.AddField(
            model_name='lifecyclereview',
            name='requires_optimization',
            field=models.BooleanField(default=False, verbose_name='Requiere optimizacion'),
        ),
        migrations.AddField(
            model_name='lifecyclereview',
            name='requires_retirement',
            field=models.BooleanField(default=False, verbose_name='Requiere baja'),
        ),
        migrations.AddField(
            model_name='lifecyclereview',
            name='requires_tuning',
            field=models.BooleanField(default=False, verbose_name='Requiere ajuste'),
        ),
        migrations.AddField(
            model_name='lifecyclereview',
            name='review_type',
            field=models.CharField(default='', max_length=40, verbose_name='Periodo'),
        ),
        migrations.AddField(
            model_name='lifecyclereview',
            name='sources_active',
            field=models.BooleanField(default=True, verbose_name='Fuentes activas'),
        ),
        migrations.AddField(
            model_name='lifecyclereview',
            name='trigger_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad de alertas'),
        ),
        migrations.AddField(
            model_name='lifecyclereview',
            name='true_incidents',
            field=models.PositiveIntegerField(default=0, verbose_name='Incidentes reales'),
        ),
        migrations.AlterField(
            model_name='lifecyclereview',
            name='result',
            field=models.CharField(blank=True, choices=[('Vigente', 'Vigente'), ('Vigente con mejoras', 'Vigente con mejoras'), ('Requiere actualizacion', 'Requiere actualizacion'), ('Obsoleta', 'Obsoleta'), ('Baja recomendada', 'Baja recomendada')], default='', max_length=80, verbose_name='Resultado'),
        ),
    ]
