# Generated by Django 6.0.5 on 2026-06-24 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifecycle', '0002_lifecyclereview_alert_triggered_90d_and_more'),
        ('usecases', '0027_alter_usecase_blocking_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LifecycleCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('closed', 'Cerrado')], default='active', max_length=20)),
                ('report_exports', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_lifecycle_cycles', to=settings.AUTH_USER_MODEL)),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_lifecycle_cycles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ciclo anual lifecycle',
                'verbose_name_plural': 'Ciclos anuales lifecycle',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='LifecyclePeriodMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('period', models.PositiveSmallIntegerField()),
                ('included_at', models.DateTimeField(auto_now_add=True)),
                ('use_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle_period_memberships', to='usecases.usecase')),
            ],
            options={
                'verbose_name': 'Miembro de periodo lifecycle',
                'verbose_name_plural': 'Miembros de periodo lifecycle',
                'ordering': ['year', 'period', 'use_case__name'],
                'constraints': [models.UniqueConstraint(fields=('year', 'period', 'use_case'), name='unique_lifecycle_period_member')],
            },
        ),
    ]
