# Generated by Django 6.0.5 on 2026-06-25 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifecycle', '0003_lifecyclecycle_lifecycleperiodmember'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lifecyclereview',
            options={'ordering': ['-checked_at', '-created_at'], 'verbose_name': 'Historial de revisión', 'verbose_name_plural': 'Historial de revisiones'},
        ),
        migrations.AlterModelOptions(
            name='lifecyclesettings',
            options={'verbose_name': 'Configuración ciclo de vida', 'verbose_name_plural': 'Configuraciones ciclo de vida'},
        ),
        migrations.AlterField(
            model_name='lifecyclereview',
            name='next_review_date',
            field=models.DateField(blank=True, null=True, verbose_name='Próximo control'),
        ),
        migrations.AlterField(
            model_name='lifecyclesettings',
            name='name',
            field=models.CharField(default='Política principal', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='lifecyclesettings',
            name='review_interval_days',
            field=models.PositiveIntegerField(default=120, verbose_name='Días entre controles'),
        ),
    ]
