# Generated by Django 6.0.5 on 2026-06-25 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifecycle', '0004_alter_lifecyclereview_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifecyclereview',
            name='logic_valid',
            field=models.BooleanField(default=True, verbose_name='Lógica funcional'),
        ),
        migrations.AlterField(
            model_name='lifecyclereview',
            name='review_type',
            field=models.CharField(default='', max_length=40, verbose_name='Período'),
        ),
    ]
