# Generated by Django 6.0.5 on 2026-06-26 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifecycle', '0005_alter_lifecyclereview_logic_valid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LifecyclePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.PositiveSmallIntegerField()),
                ('label', models.CharField(max_length=120)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configured_periods', to='lifecycle.lifecyclecycle')),
            ],
            options={
                'verbose_name': 'Periodo lifecycle',
                'verbose_name_plural': 'Periodos lifecycle',
                'ordering': ['cycle__year', 'period', 'start_date'],
                'constraints': [models.UniqueConstraint(fields=('cycle', 'period'), name='unique_lifecycle_configured_period')],
            },
        ),
    ]
