# Generated by Django 6.0.5 on 2026-06-29 14:18

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifecycle', '0006_lifecycleperiod'),
        ('usecases', '0028_usecase_full_rule_text_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LifecycleTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transition_type', models.CharField(choices=[('review_completed', 'Revision completada'), ('owner_changed', 'Responsable cambiado'), ('period_reset', 'Periodo reiniciado'), ('cycle_closed', 'Ciclo cerrado'), ('cycle_started', 'Ciclo iniciado')], max_length=32, verbose_name='Tipo')),
                ('period', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Periodo')),
                ('period_key', models.CharField(blank=True, max_length=80, verbose_name='Periodo texto')),
                ('from_state', models.CharField(blank=True, max_length=160, verbose_name='Estado anterior')),
                ('to_state', models.CharField(blank=True, max_length=160, verbose_name='Estado nuevo')),
                ('reason', models.TextField(blank=True, verbose_name='Motivo')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lifecycle_transitions', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transitions', to='lifecycle.lifecyclecycle', verbose_name='Ciclo')),
                ('review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transitions', to='lifecycle.lifecyclereview', verbose_name='Revision')),
                ('use_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lifecycle_transitions', to='usecases.usecase', verbose_name='Caso de uso')),
            ],
            options={
                'verbose_name': 'Transicion lifecycle',
                'verbose_name_plural': 'Transiciones lifecycle',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DetectionMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_key', models.CharField(blank=True, db_index=True, max_length=80, verbose_name='Periodo')),
                ('period_start', models.DateField(blank=True, null=True, verbose_name='Inicio periodo')),
                ('period_end', models.DateField(blank=True, null=True, verbose_name='Fin periodo')),
                ('measured_at', models.DateField(default=datetime.date.today, verbose_name='Fecha medicion')),
                ('trigger_count', models.PositiveIntegerField(default=0, verbose_name='Alertas')),
                ('true_incidents', models.PositiveIntegerField(default=0, verbose_name='Incidentes reales')),
                ('false_positives', models.PositiveIntegerField(default=0, verbose_name='Falsos positivos')),
                ('precision_rate', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Precision')),
                ('effectiveness_score', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Efectividad')),
                ('health_status', models.CharField(choices=[('good', 'Bueno'), ('warn', 'Atencion'), ('bad', 'Bajo'), ('unknown', 'Sin datos')], default='unknown', max_length=16, verbose_name='Estado')),
                ('source', models.CharField(choices=[('lifecycle_review', 'Revision lifecycle'), ('manual', 'Manual')], default='lifecycle_review', max_length=32, verbose_name='Origen')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_detection_metrics', to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detection_metrics', to='lifecycle.lifecyclereview', verbose_name='Revision lifecycle')),
                ('use_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detection_metrics', to='usecases.usecase', verbose_name='Caso de uso')),
            ],
            options={
                'verbose_name': 'Metrica de deteccion',
                'verbose_name_plural': 'Metricas de deteccion',
                'ordering': ['-measured_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('use_case', 'period_key', 'source'), name='unique_detection_metric_by_period_source')],
            },
        ),
    ]
