# Generated by Django 6.0.5 on 2026-06-24 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-created_at'], 'permissions': [('view_security_audit', 'Can view SOC security audit'), ('view_inventory_audit', 'Can view inventory audit'), ('view_lifecycle_audit', 'Can view lifecycle audit'), ('view_controls_audit', 'Can view controls audit'), ('view_reports_audit', 'Can view reports audit'), ('view_sigma_audit', 'Can view Sigma audit'), ('export_audit', 'Can export audit events')]},
        ),
    ]
