# Generated by Django 6.0.5 on 2026-06-23 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sources', '0002_alter_eventsource_code'),
        ('usecases', '0027_alter_usecase_blocking_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('code', models.CharField(blank=True, max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('objective', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('mitigated_risk', models.TextField(blank=True)),
                ('classification', models.CharField(choices=[('Proteccion Interna', 'Proteccion Interna'), ('Proteccion Perimetral', 'Proteccion Perimetral'), ('Proteccion Cloud', 'Proteccion Cloud')], default='Proteccion Interna', max_length=80)),
                ('status', models.CharField(choices=[('Borrador', 'Borrador'), ('Produccion', 'Produccion'), ('Mantenimiento', 'Mantenimiento'), ('Baja', 'Baja')], default='Borrador', max_length=40)),
                ('deployed_at', models.DateField(blank=True, null=True)),
                ('control_conditions', models.JSONField(blank=True, default=list)),
                ('evidence', models.TextField(blank=True)),
                ('owner', models.CharField(blank=True, max_length=150)),
                ('review_frequency_days', models.PositiveIntegerField(default=90)),
                ('next_review_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_controls', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='controls', to='sources.eventsource')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_controls', to=settings.AUTH_USER_MODEL)),
                ('use_cases', models.ManyToManyField(blank=True, related_name='controls', to='usecases.usecase')),
            ],
            options={
                'ordering': ['code', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ControlInventoryChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=40)),
                ('control_code', models.CharField(blank=True, max_length=64)),
                ('control_name', models.CharField(blank=True, max_length=255)),
                ('control_version', models.PositiveIntegerField(blank=True, null=True)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='control_inventory_changes', to=settings.AUTH_USER_MODEL)),
                ('control', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_changes', to='controls.control')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ControlVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='controls.control')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='control_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['control_id', '-version'],
            },
        ),
    ]
