# Generated by Django 6.0.5 on 2026-06-23 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usecases', '0027_alter_usecase_blocking_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SigmaConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('epl_to_sigma', 'EPL a Sigma'), ('sigma_to_target', 'Sigma a SIEM')], max_length=32)),
                ('target', models.CharField(blank=True, choices=[('netwitness', 'RSA NetWitness ESA Advanced'), ('splunk', 'Splunk Enterprise Security'), ('sentinel', 'Microsoft Sentinel'), ('elastic', 'Elastic Security'), ('qradar', 'IBM QRadar')], max_length=32)),
                ('input_text', models.TextField()),
                ('output_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sigma_conversions', to=settings.AUTH_USER_MODEL)),
                ('use_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sigma_conversions', to='usecases.usecase')),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('run_sigmaconversion', 'Can run Sigma conversions')],
            },
        ),
    ]
