# Generated by Django 6.0.5 on 2026-06-24 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigma_tools', '0001_initial'),
        ('usecases', '0027_alter_usecase_blocking_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UseCaseTechnicalBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(blank=True, verbose_name='Version')),
                ('backup_type', models.CharField(choices=[('logic', 'Logica'), ('sigma', 'Sigma'), ('both', 'Logica + Sigma')], default='both', max_length=20, verbose_name='Tipo')),
                ('title', models.CharField(blank=True, max_length=180, verbose_name='Titulo')),
                ('logic_text', models.TextField(blank=True, verbose_name='Logica / regla SIEM')),
                ('sigma_text', models.TextField(blank=True, verbose_name='Sigma')),
                ('checksum', models.CharField(editable=False, max_length=64, verbose_name='Checksum SHA-256')),
                ('is_current', models.BooleanField(default=True, verbose_name='Version vigente')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_technical_backups', to=settings.AUTH_USER_MODEL)),
                ('source_conversion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technical_backups', to='sigma_tools.sigmaconversion', verbose_name='Conversion origen')),
                ('use_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_backups', to='usecases.usecase', verbose_name='Caso de uso')),
            ],
            options={
                'verbose_name': 'Backup tecnico de caso',
                'verbose_name_plural': 'Backups tecnicos de casos',
                'ordering': ['use_case__name', '-version'],
                'permissions': [('manage_technicalbackup', 'Can manage technical backups')],
                'constraints': [models.UniqueConstraint(fields=('use_case', 'version'), name='unique_usecase_technical_backup_version')],
            },
        ),
    ]
