# Generated by Django 6.0.5 on 2026-06-25 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigma_tools', '0002_usecasetechnicalbackup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usecasetechnicalbackup',
            options={'ordering': ['use_case__name', '-version'], 'permissions': [('manage_technicalbackup', 'Can manage technical backups')], 'verbose_name': 'Backup técnico de caso', 'verbose_name_plural': 'Backups técnicos de casos'},
        ),
        migrations.AlterField(
            model_name='usecasetechnicalbackup',
            name='backup_type',
            field=models.CharField(choices=[('logic', 'Lógica'), ('sigma', 'Sigma'), ('both', 'Lógica + Sigma')], default='both', max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='usecasetechnicalbackup',
            name='is_current',
            field=models.BooleanField(default=True, verbose_name='Versión vigente'),
        ),
        migrations.AlterField(
            model_name='usecasetechnicalbackup',
            name='logic_text',
            field=models.TextField(blank=True, verbose_name='Lógica / regla SIEM'),
        ),
        migrations.AlterField(
            model_name='usecasetechnicalbackup',
            name='source_conversion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technical_backups', to='sigma_tools.sigmaconversion', verbose_name='Conversión origen'),
        ),
        migrations.AlterField(
            model_name='usecasetechnicalbackup',
            name='version',
            field=models.PositiveIntegerField(blank=True, verbose_name='Versión'),
        ),
    ]
