# Generated by Django 6.0.5 on 2026-06-23 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usecases', '0027_alter_usecase_blocking_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=64, unique=True, verbose_name='Codigo')),
                ('name', models.CharField(max_length=180, unique=True, verbose_name='Nombre')),
                ('source_type', models.CharField(choices=[('siem', 'SIEM'), ('edr', 'EDR'), ('firewall', 'Firewall'), ('identity', 'Identidad'), ('cloud', 'Cloud'), ('network', 'Red'), ('application', 'Aplicacion'), ('other', 'Otro')], default='other', max_length=40, verbose_name='Tipo')),
                ('category', models.CharField(blank=True, max_length=120, verbose_name='Categoria')),
                ('vendor', models.CharField(blank=True, max_length=120, verbose_name='Fabricante')),
                ('product', models.CharField(blank=True, max_length=160, verbose_name='Producto')),
                ('environment', models.CharField(blank=True, max_length=80, verbose_name='Ambiente')),
                ('host', models.CharField(blank=True, max_length=255, verbose_name='Host / endpoint')),
                ('port', models.PositiveIntegerField(blank=True, null=True, verbose_name='Puerto')),
                ('protocol', models.CharField(blank=True, max_length=40, verbose_name='Protocolo')),
                ('status', models.CharField(choices=[('active', 'Activa'), ('inactive', 'Inactiva'), ('planned', 'Planificada'), ('retired', 'Retirada')], default='active', max_length=20, verbose_name='Estado')),
                ('owner', models.CharField(blank=True, max_length=150, verbose_name='Responsable')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_event_sources', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_event_sources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fuente de eventos',
                'verbose_name_plural': 'Fuentes de eventos',
                'ordering': ['name'],
                'permissions': [('link_eventsource', 'Can link event sources to use cases')],
            },
        ),
        migrations.CreateModel(
            name='UseCaseSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('primary', 'Principal'), ('supporting', 'Soporte'), ('dependency', 'Dependencia'), ('context', 'Contexto')], default='primary', max_length=24, verbose_name='Rol')),
                ('is_required', models.BooleanField(default=True, verbose_name='Obligatoria')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_usecase_sources', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='use_case_links', to='sources.eventsource', verbose_name='Fuente')),
                ('use_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_links', to='usecases.usecase', verbose_name='Caso de uso')),
            ],
            options={
                'verbose_name': 'Fuente por caso de uso',
                'verbose_name_plural': 'Fuentes por caso de uso',
                'ordering': ['use_case__name', 'source__name'],
                'constraints': [models.UniqueConstraint(fields=('use_case', 'source'), name='unique_usecase_event_source')],
            },
        ),
    ]
