# Generated by Django 6.0.5 on 2026-06-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsource',
            name='code',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Codigo'),
        ),
    ]
