# Generated by Django 6.0.5 on 2026-06-24 13:18

import django.db.models.deletion
from django.db import migrations, models


def migrate_existing_categories(apps, schema_editor):
    EventSource = apps.get_model("sources", "EventSource")
    SourceCategory = apps.get_model("sources", "SourceCategory")
    names = (
        EventSource.objects
        .exclude(category="")
        .values_list("category", flat=True)
        .distinct()
    )
    category_map = {}
    for raw_name in names:
        name = (raw_name or "").strip()
        if not name:
            continue
        category, _ = SourceCategory.objects.get_or_create(name=name, parent=None)
        category_map[name.casefold()] = category
    for source in EventSource.objects.exclude(category=""):
        category = category_map.get((source.category or "").strip().casefold())
        if category:
            source.category_ref_id = category.id
            source.save(update_fields=["category_ref"])


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0002_alter_eventsource_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcategories', to='sources.sourcecategory', verbose_name='Categoria padre')),
            ],
            options={
                'verbose_name': 'Categoria de fuente',
                'verbose_name_plural': 'Categorias de fuentes',
                'ordering': ['parent__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='eventsource',
            name='category_ref',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'parent__isnull': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sources', to='sources.sourcecategory', verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='eventsource',
            name='subcategory_ref',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'parent__isnull': False}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcategory_sources', to='sources.sourcecategory', verbose_name='Subcategoria'),
        ),
        migrations.RunPython(migrate_existing_categories, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='sourcecategory',
            constraint=models.UniqueConstraint(fields=('parent', 'name'), name='unique_source_category_parent_name'),
        ),
    ]
