# Generated by Django 6.0.5 on 2026-06-24 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0003_sourcecategory_eventsource_category_ref_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sourcecategory',
            name='unique_source_category_parent_name',
        ),
        migrations.AddConstraint(
            model_name='sourcecategory',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('name',), name='unique_root_source_category_name'),
        ),
        migrations.AddConstraint(
            model_name='sourcecategory',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', False)), fields=('parent', 'name'), name='unique_child_source_category_name'),
        ),
    ]
