# Generated by Django 6.0.5 on 2026-06-25 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0005_sourcetype_alter_eventsource_source_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sourcecategory',
            options={'ordering': ['parent__name', 'name'], 'verbose_name': 'Categoría de fuente', 'verbose_name_plural': 'Categorías de fuentes'},
        ),
        migrations.AlterField(
            model_name='eventsource',
            name='category',
            field=models.CharField(blank=True, max_length=120, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='eventsource',
            name='category_ref',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'parent__isnull': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sources', to='sources.sourcecategory', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='eventsource',
            name='code',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='eventsource',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='eventsource',
            name='subcategory_ref',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'parent__isnull': False}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcategory_sources', to='sources.sourcecategory', verbose_name='Subcategoría'),
        ),
        migrations.AlterField(
            model_name='sourcecategory',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='sourcecategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcategories', to='sources.sourcecategory', verbose_name='Categoría padre'),
        ),
        migrations.AlterField(
            model_name='sourcetype',
            name='code',
            field=models.SlugField(max_length=40, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='sourcetype',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
    ]
