# Generated by Django 5.2.15 on 2026-07-24 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_heatmap', '0002_serverasset_legacy_inventory_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventorySyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('ad', 'Active Directory'), ('siem', 'SIEM'), ('legacy', 'Importación anterior')], max_length=20, verbose_name='Origen')),
                ('status', models.CharField(choices=[('running', 'En ejecución'), ('success', 'Finalizada'), ('failed', 'Fallida')], default='running', max_length=20, verbose_name='Estado')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Inicio')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Fin')),
                ('records_read', models.PositiveIntegerField(default=0, verbose_name='Registros leídos')),
                ('assets_created', models.PositiveIntegerField(default=0, verbose_name='Equipos creados')),
                ('assets_updated', models.PositiveIntegerField(default=0, verbose_name='Equipos actualizados')),
                ('issues_count', models.PositiveIntegerField(default=0, verbose_name='Conflictos')),
                ('error_message', models.TextField(blank=True, verbose_name='Error')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadatos')),
            ],
            options={
                'verbose_name': 'Ejecución de inventario',
                'verbose_name_plural': 'Ejecuciones de inventario',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='serverasset',
            name='ad_last_seen_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última observación AD'),
        ),
        migrations.AddField(
            model_name='serverasset',
            name='siem_last_seen_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última observación SIEM'),
        ),
        migrations.CreateModel(
            name='InventoryObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('ad', 'Active Directory'), ('siem', 'SIEM'), ('legacy', 'Importación anterior')], max_length=20, verbose_name='Origen')),
                ('external_id', models.CharField(max_length=255, verbose_name='Identificador externo')),
                ('hostname', models.CharField(blank=True, max_length=255, verbose_name='Hostname')),
                ('fqdn', models.CharField(blank=True, max_length=255, verbose_name='FQDN')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('os_name', models.CharField(blank=True, max_length=180, verbose_name='Sistema operativo')),
                ('organizational_unit', models.CharField(blank=True, max_length=500, verbose_name='Unidad organizativa (OU)')),
                ('environment', models.CharField(blank=True, max_length=80, verbose_name='Ambiente')),
                ('groups', models.TextField(blank=True, verbose_name='Grupos')),
                ('server_type_hint', models.CharField(blank=True, max_length=80, verbose_name='Tipo sugerido')),
                ('observed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha observada')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='Dato original')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_observations', to='server_heatmap.serverasset', verbose_name='Equipo conciliado')),
                ('sync_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='server_heatmap.inventorysyncrun', verbose_name='Ejecución')),
            ],
            options={
                'verbose_name': 'Observación de inventario',
                'verbose_name_plural': 'Observaciones de inventario',
                'ordering': ['hostname', 'external_id'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('ambiguous', 'Coincidencia ambigua'), ('missing_identifier', 'Sin identificador'), ('invalid', 'Dato inválido')], max_length=40, verbose_name='Tipo')),
                ('identifier', models.CharField(blank=True, max_length=255, verbose_name='Identificador')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Detalle')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Resuelto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('observation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='server_heatmap.inventoryobservation', verbose_name='Observación')),
                ('sync_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='server_heatmap.inventorysyncrun', verbose_name='Ejecución')),
            ],
            options={
                'verbose_name': 'Conflicto de conciliación',
                'verbose_name_plural': 'Conflictos de conciliación',
                'ordering': ['is_resolved', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('hostname', 'Hostname'), ('fqdn', 'FQDN'), ('ip', 'Dirección IP')], max_length=20, verbose_name='Tipo')),
                ('value', models.CharField(max_length=255, verbose_name='Valor')),
                ('normalized_value', models.CharField(db_index=True, max_length=255, verbose_name='Valor normalizado')),
                ('source', models.CharField(choices=[('ad', 'Active Directory'), ('siem', 'SIEM'), ('legacy', 'Importación anterior')], max_length=20, verbose_name='Origen')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='Última observación')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='server_heatmap.serverasset')),
            ],
            options={
                'verbose_name': 'Identificador de equipo',
                'verbose_name_plural': 'Identificadores de equipos',
                'indexes': [models.Index(fields=['kind', 'normalized_value'], name='server_heat_kind_874431_idx')],
                'constraints': [models.UniqueConstraint(fields=('asset', 'kind', 'normalized_value', 'source'), name='uniq_asset_identifier_source')],
            },
        ),
        migrations.AddConstraint(
            model_name='inventoryobservation',
            constraint=models.UniqueConstraint(fields=('sync_run', 'source', 'external_id'), name='uniq_inventory_observation_per_run'),
        ),
    ]
