# Generated by Django 5.2.15 on 2026-07-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_heatmap', '0003_inventorysyncrun_serverasset_ad_last_seen_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reconciliationissue',
            name='issue_type',
            field=models.CharField(choices=[('ambiguous', 'Coincidencia ambigua'), ('missing_identifier', 'Sin identificador'), ('not_in_ad', 'No encontrado en AD'), ('invalid', 'Dato inválido')], max_length=40, verbose_name='Tipo'),
        ),
    ]
