# Generated by Django 5.2.15 on 2026-07-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_heatmap', '0004_alter_reconciliationissue_issue_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverasset',
            name='ad_last_logon_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última actividad AD'),
        ),
        migrations.AddField(
            model_name='serverasset',
            name='dns_status',
            field=models.CharField(choices=[('unchecked', 'Sin verificar'), ('resolved', 'Resuelto'), ('failed', 'No resuelto')], default='unchecked', max_length=20, verbose_name='Estado DNS'),
        ),
        migrations.AddField(
            model_name='serverasset',
            name='network_check_error',
            field=models.TextField(blank=True, verbose_name='Detalle del diagnóstico'),
        ),
        migrations.AddField(
            model_name='serverasset',
            name='network_checked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último diagnóstico de red'),
        ),
        migrations.AddField(
            model_name='serverasset',
            name='reachability_status',
            field=models.CharField(choices=[('unchecked', 'Sin verificar'), ('reachable', 'Responde'), ('unreachable', 'No responde'), ('error', 'No disponible')], default='unchecked', max_length=20, verbose_name='Estado de conectividad'),
        ),
        migrations.AddField(
            model_name='serverasset',
            name='resolved_fqdn',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nombre resuelto'),
        ),
        migrations.AddField(
            model_name='serverasset',
            name='resolved_ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP resuelta'),
        ),
    ]
