# Generated by Django 5.2.15 on 2026-07-24 19:42

from django.db import migrations, models


def create_default_inventory_configuration(apps, schema_editor):
    configuration = apps.get_model("server_heatmap", "ServerInventoryConfiguration")
    configuration.objects.get_or_create(pk=1, defaults={"ad_active_days": 60})


class Migration(migrations.Migration):

    dependencies = [
        ('server_heatmap', '0005_serverasset_ad_last_logon_at_serverasset_dns_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerInventoryConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_active_days', models.PositiveSmallIntegerField(default=60, help_text='Solo se importan equipos habilitados cuya última actividad en Active Directory esté dentro de este período. Use 0 para no filtrar por fecha.', verbose_name='Actividad máxima en AD (días)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del inventario',
                'verbose_name_plural': 'Configuración del inventario',
            },
        ),
        migrations.RunPython(
            create_default_inventory_configuration,
            migrations.RunPython.noop,
        ),
        migrations.AddField(
            model_name='servernamingrule',
            name='match_type',
            field=models.CharField(choices=[('wildcard', 'Comodín simple (* y ?)'), ('regex', 'Expresión regular avanzada')], default='regex', max_length=20, verbose_name='Tipo de patrón'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servernamingrule',
            name='match_type',
            field=models.CharField(choices=[('wildcard', 'Comodín simple (* y ?)'), ('regex', 'Expresión regular avanzada')], default='wildcard', max_length=20, verbose_name='Tipo de patrón'),
        ),
        migrations.AlterField(
            model_name='servernamingrule',
            name='pattern',
            field=models.CharField(help_text='No distingue mayúsculas. Ejemplo con comodín: arpads*', max_length=255, verbose_name='Patrón del nombre'),
        ),
    ]
