# Generated by Django 5.2.15 on 2026-07-24 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_heatmap', '0006_serverinventoryconfiguration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverinventoryconfiguration',
            name='retention_days',
            field=models.PositiveSmallIntegerField(default=90, help_text='Después de una sincronización AD exitosa se eliminan los equipos cuya última actividad AD sea anterior a este período. Use 0 para no eliminar.', verbose_name='Eliminar equipos sin conexión después de (días)'),
        ),
    ]
