# Generated by Django 5.2.15 on 2026-07-27 02:57

import django.db.models.deletion
from django.db import migrations, models


def seed_server_categories(apps, schema_editor):
    category_model = apps.get_model("server_heatmap", "ServerCategory")
    asset_model = apps.get_model("server_heatmap", "ServerAsset")
    rule_model = apps.get_model("server_heatmap", "ServerNamingRule")
    definitions = [
        ("ad", "Domain Controllers", 10),
        ("fileserver", "File Server", 20),
        ("database", "Base de datos", 30),
        ("exchange", "Exchange", 40),
        ("application", "Aplicaciones", 50),
        ("web", "Web", 60),
        ("security", "Seguridad", 70),
        ("network", "Red / infraestructura", 80),
        ("other", "Otro", 90),
        ("unknown", "Sin identificar", 999),
    ]
    categories = {}
    for code, name, order in definitions:
        categories[code], _ = category_model.objects.get_or_create(
            code=code,
            defaults={"name": name, "order": order, "is_active": True},
        )
    for legacy_type in (
        "ad", "fileserver", "database", "application", "web",
        "security", "network", "other", "unknown",
    ):
        asset_model.objects.filter(server_type=legacy_type).update(category=categories[legacy_type])
        rule_model.objects.filter(server_type=legacy_type).update(category=categories[legacy_type])
    asset_model.objects.filter(server_type="mail").update(category=categories["exchange"])
    rule_model.objects.filter(server_type="mail").update(category=categories["exchange"])


class Migration(migrations.Migration):

    dependencies = [
        ('server_heatmap', '0007_serverinventoryconfiguration_retention_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('code', models.SlugField(help_text='Identificador interno estable. Ejemplo: domain-controllers.', max_length=60, unique=True, verbose_name='Código')),
                ('order', models.PositiveSmallIntegerField(default=100, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Sección de servidores',
                'verbose_name_plural': 'Secciones de servidores',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='serverasset',
            name='server_type',
            field=models.CharField(choices=[('ad', 'Domain Controllers'), ('application', 'Aplicaciones'), ('database', 'Base de datos'), ('fileserver', 'File server'), ('web', 'Web'), ('mail', 'Correo'), ('security', 'Seguridad'), ('network', 'Red / infraestructura'), ('other', 'Otro'), ('unknown', 'Sin identificar')], default='unknown', max_length=30, verbose_name='Tipo de servidor'),
        ),
        migrations.AlterField(
            model_name='servernamingrule',
            name='server_type',
            field=models.CharField(blank=True, choices=[('ad', 'Domain Controllers'), ('application', 'Aplicaciones'), ('database', 'Base de datos'), ('fileserver', 'File server'), ('web', 'Web'), ('mail', 'Correo'), ('security', 'Seguridad'), ('network', 'Red / infraestructura'), ('other', 'Otro'), ('unknown', 'Sin identificar')], max_length=30, verbose_name='Tipo sugerido'),
        ),
        migrations.AddField(
            model_name='serverasset',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='server_heatmap.servercategory', verbose_name='Sección funcional'),
        ),
        migrations.AddField(
            model_name='servernamingrule',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='naming_rules', to='server_heatmap.servercategory', verbose_name='Sección funcional sugerida'),
        ),
        migrations.RunPython(seed_server_categories, migrations.RunPython.noop),
    ]
