# Generated by Django 5.2.15 on 2026-07-27 19:56

import django.db.models.deletion
from django.db import migrations, models


def seed_inactive_reference_filters(apps, schema_editor):
    rule_model = apps.get_model("server_heatmap", "InventoryFilterRule")
    category_model = apps.get_model("server_heatmap", "ServerCategory")
    for position, prefix in enumerate(
        ("ltp", "vd", "vt", "ks", "st", "dr", "arm", "d-", "nic", "sql", "dsk", "sala", "xd", "dd", "w2"),
        start=1,
    ):
        rule_model.objects.get_or_create(
            name=f"Referencia anterior: excluir {prefix}*",
            defaults={
                "source": "ad",
                "field": "hostname",
                "operator": "wildcard",
                "pattern": f"{prefix}*",
                "action": "exclude",
                "priority": 500 + position,
                "is_active": False,
                "reason": "Regla recuperada del sistema anterior. Revisar la vista previa antes de activar.",
            },
        )
    domain_controllers = category_model.objects.filter(code="ad").first()
    if domain_controllers:
        rule_model.objects.get_or_create(
            name="OU Domain Controllers",
            defaults={
                "source": "ad",
                "field": "organizational_unit",
                "operator": "contains",
                "pattern": "Domain Controllers",
                "action": "classify",
                "category": domain_controllers,
                "priority": 20,
                "is_active": False,
                "reason": "La OU de Active Directory es la señal principal para identificar DC.",
            },
        )
    security = category_model.objects.filter(code="security").first()
    if security:
        for position, keyword in enumerate(
            (
                "checkpoint", "juniper", "f5", "mcafee", "netscaler", "password",
                "guardium", "prisma", "proxy", "casb", "trellix", "citrix",
                "cisco", "forcepoint", "tenable", "ndr",
            ),
            start=1,
        ):
            rule_model.objects.get_or_create(
                name=f"Grupo SIEM de seguridad: {keyword}",
                defaults={
                    "source": "siem",
                    "field": "groups",
                    "operator": "word",
                    "pattern": keyword,
                    "action": "classify",
                    "category": security,
                    "priority": 100 + position,
                    "is_active": False,
                    "reason": "Keyword histórica centralizada. Validar coincidencias antes de activar.",
                },
            )
    rule_model.objects.get_or_create(
        name="Tipo SIEM unknown para revisión",
        defaults={
            "source": "siem",
            "field": "server_type_hint",
            "operator": "exact",
            "pattern": "unknown",
            "action": "exclude",
            "priority": 400,
            "is_active": False,
            "reason": "Referencia anterior. No activar sin revisar los dispositivos afectados.",
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('server_heatmap', '0008_servercategory_alter_serverasset_server_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryFilterRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, unique=True, verbose_name='Nombre')),
                ('source', models.CharField(choices=[('both', 'AD y SIEM'), ('ad', 'Active Directory'), ('siem', 'SIEM')], default='both', max_length=20, verbose_name='Origen')),
                ('field', models.CharField(choices=[('hostname', 'Hostname'), ('fqdn', 'FQDN'), ('ip_address', 'Dirección IP'), ('organizational_unit', 'Unidad organizativa (OU)'), ('os_name', 'Sistema operativo informado'), ('groups', 'Grupos SIEM'), ('server_type_hint', 'Tipo de dispositivo SIEM'), ('environment', 'Ambiente')], max_length=40, verbose_name='Campo evaluado')),
                ('operator', models.CharField(choices=[('exact', 'Igual'), ('contains', 'Contiene'), ('wildcard', 'Comodín (* y ?)'), ('regex', 'Expresión regular'), ('word', 'Palabra completa')], default='wildcard', max_length=20, verbose_name='Operador')),
                ('pattern', models.CharField(max_length=500, verbose_name='Patrón')),
                ('action', models.CharField(choices=[('exclude', 'Excluir'), ('include', 'Incluir'), ('classify', 'Clasificar')], max_length=20, verbose_name='Acción')),
                ('os_family', models.CharField(blank=True, choices=[('windows', 'Windows'), ('linux', 'Linux'), ('unix', 'Unix'), ('other', 'Otro'), ('unknown', 'Sin identificar')], max_length=20, verbose_name='Sistema operativo asignado')),
                ('environment_value', models.CharField(blank=True, max_length=80, verbose_name='Ambiente asignado')),
                ('priority', models.PositiveIntegerField(default=100, help_text='Las reglas con menor número se evalúan primero.', verbose_name='Prioridad')),
                ('is_active', models.BooleanField(default=False, verbose_name='Activa')),
                ('reason', models.TextField(blank=True, verbose_name='Motivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_filter_rules', to='server_heatmap.servercategory', verbose_name='Sección asignada')),
            ],
            options={
                'verbose_name': 'Filtro de inventario',
                'verbose_name_plural': 'Filtros de inventario',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryFilterDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('ad', 'Active Directory'), ('siem', 'SIEM'), ('legacy', 'Importación anterior')], max_length=20, verbose_name='Origen')),
                ('identifier', models.CharField(blank=True, max_length=255, verbose_name='Identificador')),
                ('action', models.CharField(choices=[('exclude', 'Excluir'), ('include', 'Incluir'), ('classify', 'Clasificar')], max_length=20, verbose_name='Acción')),
                ('reason', models.TextField(blank=True, verbose_name='Motivo')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='Datos originales')),
                ('is_reviewed', models.BooleanField(default=False, verbose_name='Revisada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sync_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filter_decisions', to='server_heatmap.inventorysyncrun', verbose_name='Ejecución')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions', to='server_heatmap.inventoryfilterrule', verbose_name='Regla aplicada')),
            ],
            options={
                'verbose_name': 'Decisión de filtro',
                'verbose_name_plural': 'Decisiones de filtros',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(
            seed_inactive_reference_filters,
            migrations.RunPython.noop,
        ),
    ]
