# Generated by Django 6.0.5 on 2026-06-21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("usecases", "0025_alter_mitreattacksyncsettings_options"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name="DashboardReportSettings",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("is_active", models.BooleanField(default=True)),
                        ("name", models.CharField(default="Reporte principal", max_length=100, unique=True)),
                        ("logo", models.ImageField(blank=True, upload_to="dashboard_reports/logos/", verbose_name="Logo")),
                        ("report_title", models.CharField(default="Reporte ejecutivo SOC", max_length=160, verbose_name="TÃ­tulo")),
                        ("report_subtitle", models.CharField(blank=True, default="Cobertura ATT&CK y D3FEND sobre casos de uso en producciÃ³n", max_length=255, verbose_name="SubtÃ­tulo")),
                        ("footer_text", models.CharField(blank=True, default="SOC Use Cases Manager", max_length=255, verbose_name="Pie de pÃ¡gina")),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                    ],
                    options={
                        "verbose_name": "ConfiguraciÃ³n reporte dashboard",
                        "verbose_name_plural": "Configuraciones reporte dashboard",
                        "db_table": "usecases_dashboardreportsettings",
                        "constraints": [
                            models.UniqueConstraint(condition=models.Q(("is_active", True)), fields=("is_active",), name="unique_active_dashboard_report_settings"),
                        ],
                    },
                ),
            ],
        ),
    ]
