# Generated by Django 6.0.5 on 2026-06-23 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboardreportsettings',
            options={'permissions': [('view_executive_dashboard', 'Can view executive dashboard'), ('view_mitre_dashboard', 'Can view MITRE dashboard')], 'verbose_name': 'ConfiguraciÃ³n reporte dashboard', 'verbose_name_plural': 'Configuraciones reporte dashboard'},
        ),
    ]
