# Generated by Django 6.0.5 on 2026-06-25 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_dashboardreportsettings_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboardreportsettings',
            options={'permissions': [('view_executive_dashboard', 'Can view executive dashboard'), ('view_mitre_dashboard', 'Can view MITRE dashboard')], 'verbose_name': 'Configuración reporte dashboard', 'verbose_name_plural': 'Configuraciones reporte dashboard'},
        ),
        migrations.AlterField(
            model_name='dashboardreportsettings',
            name='footer_text',
            field=models.CharField(blank=True, default='SOC Use Cases Manager', max_length=255, verbose_name='Pie de página'),
        ),
        migrations.AlterField(
            model_name='dashboardreportsettings',
            name='report_subtitle',
            field=models.CharField(blank=True, default='Cobertura ATT&CK y D3FEND sobre casos de uso en producción', max_length=255, verbose_name='Subtítulo'),
        ),
        migrations.AlterField(
            model_name='dashboardreportsettings',
            name='report_title',
            field=models.CharField(default='Reporte ejecutivo SOC', max_length=160, verbose_name='Título'),
        ),
    ]
