# Generated by Django 6.0.5 on 2026-06-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_dashboardreportsettings_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MitreCoverageSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(unique=True, verbose_name='Fecha')),
                ('coverage_score', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Estado cobertura')),
                ('attack_techniques_covered', models.PositiveIntegerField(default=0)),
                ('attack_techniques_total', models.PositiveIntegerField(default=0)),
                ('attack_techniques_percent', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('attack_tactics_full_covered', models.PositiveIntegerField(default=0)),
                ('attack_tactics_total', models.PositiveIntegerField(default=0)),
                ('attack_tactics_percent', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('d3fend_detect_equivalent_covered', models.DecimalField(decimal_places=1, default=0, max_digits=8)),
                ('d3fend_detect_total', models.PositiveIntegerField(default=0)),
                ('d3fend_detect_percent', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('d3fend_detect_full_covered', models.PositiveIntegerField(default=0)),
                ('d3fend_detect_full_percent', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Snapshot cobertura MITRE',
                'verbose_name_plural': 'Snapshots cobertura MITRE',
                'ordering': ['snapshot_date'],
            },
        ),
    ]
