# Generated by Django 5.1.7 on 2026-04-11 03:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UseCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(blank=True, max_length=100, verbose_name='Grupo')),
                ('device', models.CharField(blank=True, max_length=150, verbose_name='Dispositivo')),
                ('case_type', models.CharField(blank=True, max_length=100, verbose_name='Tipo')),
                ('objective', models.TextField(blank=True, verbose_name='Objetivo')),
                ('blocking_type', models.CharField(blank=True, max_length=100, verbose_name='Tipo de bloqueo')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre NetWitness')),
                ('owner_name', models.CharField(blank=True, max_length=150, verbose_name='Responsable')),
                ('monitoring', models.CharField(blank=True, max_length=100, verbose_name='Monitoreo')),
                ('status', models.CharField(blank=True, max_length=100, verbose_name='Estado')),
                ('created_or_adjusted_at', models.DateField(blank=True, null=True, verbose_name='Fecha alta/ajuste')),
                ('production_date', models.DateField(blank=True, null=True, verbose_name='Fecha puesta en producción')),
                ('mitre_attack', models.CharField(blank=True, max_length=255, verbose_name='MITRE ATT&CK')),
                ('d3fend_code', models.CharField(blank=True, max_length=100, verbose_name='D3FEND')),
                ('severity', models.CharField(blank=True, max_length=50, verbose_name='Severidad')),
                ('escalation', models.CharField(blank=True, max_length=100, verbose_name='Escalamiento')),
                ('sent_to_ho', models.CharField(blank=True, max_length=50, verbose_name='Envío HO')),
                ('ho_flag', models.CharField(blank=True, max_length=50, verbose_name='HO')),
                ('last_review_date', models.DateField(blank=True, null=True, verbose_name='Última revisión')),
                ('next_review_date', models.DateField(blank=True, null=True, verbose_name='Próxima revisión')),
                ('comments', models.TextField(blank=True, verbose_name='Comentarios')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_usecases', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_usecases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'permissions': [('approve_usecase', 'Can approve use case'), ('promote_usecase', 'Can promote use case to production'), ('review_usecase', 'Can review use case'), ('retire_usecase', 'Can retire use case')],
            },
        ),
    ]
