# Generated by Django 5.1.7 on 2026-04-11 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usecases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usecase',
            name='is_enabled',
            field=models.BooleanField(default=True, verbose_name='Habilitado'),
        ),
        migrations.AddField(
            model_name='usecase',
            name='last_check_date',
            field=models.DateField(blank=True, null=True, verbose_name='Última comprobación'),
        ),
        migrations.AddField(
            model_name='usecase',
            name='last_check_result',
            field=models.CharField(choices=[('Not Checked', 'Not Checked'), ('OK', 'OK'), ('Warning', 'Warning'), ('Failed', 'Failed')], default='Not Checked', max_length=20, verbose_name='Resultado última comprobación'),
        ),
        migrations.AddField(
            model_name='usecase',
            name='lifecycle_status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Development', 'Development'), ('Testing', 'Testing'), ('Validation', 'Validation'), ('Production', 'Production'), ('Tuning', 'Tuning'), ('Disabled', 'Disabled'), ('Retired', 'Retired')], default='Draft', max_length=20, verbose_name='Lifecycle'),
        ),
    ]
