# Generated by Django 5.1.7 on 2026-04-11 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usecases', '0002_usecase_is_enabled_usecase_last_check_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usecase',
            name='blocking_type',
            field=models.CharField(blank=True, choices=[('Manual', 'Manual'), ('Automático', 'Automático'), ('Semiautomático', 'Semiautomático')], max_length=20, verbose_name='Tipo de bloqueo'),
        ),
        migrations.AlterField(
            model_name='usecase',
            name='escalation',
            field=models.CharField(blank=True, choices=[('IRT', 'IRT'), ('SOC', 'SOC'), ('Otro', 'Otro')], max_length=10, verbose_name='Escalamiento'),
        ),
        migrations.AlterField(
            model_name='usecase',
            name='sent_to_ho',
            field=models.CharField(blank=True, choices=[('Sí', 'Sí'), ('No', 'No')], max_length=3, verbose_name='Envío HO'),
        ),
        migrations.AlterField(
            model_name='usecase',
            name='status',
            field=models.CharField(blank=True, choices=[('Test', 'Test'), ('Producción', 'Producción'), ('Desarrollo', 'Desarrollo'), ('Baja', 'Baja'), ('Propuesta', 'Propuesta')], max_length=20, verbose_name='Estado'),
        ),
    ]
