# Generated by Django 5.1.7 on 2026-04-11 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usecases', '0003_alter_usecase_blocking_type_alter_usecase_escalation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usecase',
            name='last_check_date',
        ),
        migrations.RemoveField(
            model_name='usecase',
            name='last_check_result',
        ),
        migrations.RemoveField(
            model_name='usecase',
            name='lifecycle_status',
        ),
        migrations.AddField(
            model_name='usecase',
            name='last_validation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Última validación'),
        ),
        migrations.AddField(
            model_name='usecase',
            name='validation_result',
            field=models.CharField(choices=[('Nada', 'Nada'), ('OK', 'OK'), ('Advertencia', 'Advertencia'), ('Falló', 'Falló')], default='Nada', max_length=20, verbose_name='Resultado'),
        ),
        migrations.AddField(
            model_name='usecase',
            name='validation_status',
            field=models.CharField(choices=[('Finalizado', 'Finalizado'), ('En progreso', 'En progreso'), ('No realizado', 'No realizado')], default='No realizado', max_length=20, verbose_name='Estado de validación'),
        ),
    ]
