# Generated by Django 5.1.7 on 2026-04-12 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usecases', '0004_remove_usecase_last_check_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usecase',
            name='severity',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], max_length=20, verbose_name='Severidad'),
        ),
    ]
