# Generated by Django 5.1.7 on 2026-04-12 04:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usecases', '0005_alter_usecase_severity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UseCaseChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100, verbose_name='Campo')),
                ('old_value', models.TextField(blank=True, verbose_name='Valor anterior')),
                ('new_value', models.TextField(blank=True, verbose_name='Valor nuevo')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha cambio')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usecase_changes', to=settings.AUTH_USER_MODEL)),
                ('use_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='usecases.usecase')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
