# Generated by Django 5.1.7 on 2026-04-12 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usecases', '0006_usecasechangelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='D3Fend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Código D3FEND')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Nombre')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Categoría')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='MitreAttack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=20, unique=True, verbose_name='ID ATT&CK')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('tactic', models.CharField(blank=True, max_length=100, verbose_name='Táctica')),
            ],
            options={
                'ordering': ['external_id'],
            },
        ),
        migrations.RemoveField(
            model_name='usecase',
            name='d3fend_code',
        ),
        migrations.RemoveField(
            model_name='usecase',
            name='mitre_attack',
        ),
        migrations.AddField(
            model_name='usecase',
            name='d3fends',
            field=models.ManyToManyField(blank=True, related_name='use_cases', to='usecases.d3fend', verbose_name='D3FEND relacionado'),
        ),
        migrations.AddField(
            model_name='usecase',
            name='mitre_attacks',
            field=models.ManyToManyField(blank=True, related_name='use_cases', to='usecases.mitreattack', verbose_name='MITRE ATT&CK relacionado'),
        ),
    ]
