# Generated by Django 5.1.7 on 2026-05-03 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usecases", "0007_d3fend_mitreattack_remove_usecase_d3fend_code_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LifecycleSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Política principal", max_length=100, unique=True
                    ),
                ),
                (
                    "review_interval_days",
                    models.PositiveIntegerField(
                        default=120, verbose_name="Días entre controles"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Configuración ciclo de vida",
                "verbose_name_plural": "Configuraciones ciclo de vida",
            },
        ),
    ]
