# Generated by Django 5.1.7 on 2026-05-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usecases", "0008_lifecyclesettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="d3fend",
            name="is_enabled",
            field=models.BooleanField(default=True, verbose_name="Habilitada"),
        ),
        migrations.AddField(
            model_name="mitreattack",
            name="is_enabled",
            field=models.BooleanField(default=True, verbose_name="Habilitada"),
        ),
    ]
