# Generated by Django 5.1.7 on 2026-05-05 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usecases", "0009_d3fend_is_enabled_mitreattack_is_enabled"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="usecase",
            name="lifecycle_control_owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lifecycle_control_usecases",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Responsable control",
            ),
        ),
        migrations.AlterField(
            model_name="usecase",
            name="owner_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Responsable desarrollo"
            ),
        ),
    ]
