# Generated by Django 6.0.5 on 2026-05-17 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usecases', '0014_d3fend_related_attacks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='d3fend',
            name='code',
            field=models.CharField(max_length=120, unique=True, verbose_name='Código D3FEND'),
        ),
    ]
