# Generated by Django 6.0.5 on 2026-05-18 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usecases', '0015_alter_d3fend_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='d3fend',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Descripción de la técnica D3FEND.', verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='d3fend',
            name='disabled_reason',
            field=models.TextField(blank=True, default='', help_text='Explica por qué esta técnica D3FEND fue deshabilitada.', verbose_name='Motivo de deshabilitación'),
        ),
        migrations.AddField(
            model_name='d3fend',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Notas internas sobre la técnica D3FEND o su aplicabilidad en el SOC.', verbose_name='Notas internas'),
        ),
    ]
