# Generated by Django 6.0.5 on 2026-05-18 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usecases', '0016_d3fend_description_d3fend_disabled_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mitreattack',
            name='disabled_reason',
            field=models.TextField(blank=True, default='', help_text='Explica por qué esta técnica ATT&CK fue deshabilitada.', verbose_name='Motivo de deshabilitación'),
        ),
        migrations.AddField(
            model_name='mitreattack',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Notas internas sobre la técnica ATT&CK o su aplicabilidad en el SOC.', verbose_name='Notas internas'),
        ),
    ]
