# Generated by Django 6.0.5 on 2026-05-19 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usecases', '0019_mitreattack_disabled_reason_mitreattack_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mitreattack',
            name='disabled_reason',
        ),
        migrations.RemoveField(
            model_name='mitreattack',
            name='notes',
        ),
    ]
