# Generated by Django 6.0.5 on 2026-05-20 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usecases', '0020_remove_mitreattack_disabled_reason_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='d3fend',
            options={'ordering': ['code'], 'verbose_name': 'D3FEND', 'verbose_name_plural': 'D3FEND'},
        ),
        migrations.AlterModelOptions(
            name='mitreattack',
            options={'ordering': ['external_id'], 'verbose_name': 'MITRE ATT&CK', 'verbose_name_plural': 'MITRE ATT&CK'},
        ),
        migrations.AddField(
            model_name='mitreattack',
            name='disabled_reason',
            field=models.TextField(blank=True, default='', help_text='Explica por qué esta técnica ATT&CK fue deshabilitada.', verbose_name='Motivo de deshabilitación'),
        ),
        migrations.AddField(
            model_name='mitreattack',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Notas internas sobre la técnica ATT&CK o su aplicabilidad en el SOC.', verbose_name='Notas internas'),
        ),
    ]
