# Generated by Django 6.0.5 on 2026-05-26 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usecases', '0023_coverageoverride'),
    ]

    operations = [
        migrations.CreateModel(
            name='MitreAttackSyncSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(default='Sincronizacion MITRE principal', max_length=100, unique=True)),
                ('interval_value', models.PositiveIntegerField(default=24, verbose_name='Intervalo')),
                ('interval_unit', models.CharField(choices=[('hours', 'Horas'), ('days', 'Dias')], default='hours', max_length=10, verbose_name='Unidad')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='Ultima ejecucion')),
                ('last_success_at', models.DateTimeField(blank=True, null=True, verbose_name='Ultima ejecucion OK')),
                ('last_status', models.CharField(choices=[('never', 'Nunca ejecutado'), ('running', 'En ejecucion'), ('success', 'OK'), ('error', 'Error')], default='never', max_length=20, verbose_name='Ultimo estado')),
                ('last_message', models.TextField(blank=True, default='', verbose_name='Ultimo mensaje')),
                ('last_created', models.PositiveIntegerField(default=0, verbose_name='Ultimos creados')),
                ('last_updated', models.PositiveIntegerField(default=0, verbose_name='Ultimos actualizados')),
                ('last_skipped', models.PositiveIntegerField(default=0, verbose_name='Ultimos omitidos')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuracion sync MITRE',
                'verbose_name_plural': 'Configuraciones sync MITRE',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='unique_active_mitre_attack_sync_settings')],
            },
        ),
    ]
