# Generated by Django 6.0.5 on 2026-06-18 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usecases', '0024_mitreattacksyncsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mitreattacksyncsettings',
            options={'verbose_name': 'Sincronizacion de frameworks', 'verbose_name_plural': 'Sincronizaciones de frameworks'},
        ),
    ]
