# Generated by Django 6.0.5 on 2026-06-21 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usecases', '0026_split_domain_model_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usecase',
            name='blocking_type',
            field=models.CharField(blank=True, choices=[('Manual', 'Manual'), ('Automático', 'Automático'), ('Semiautomático', 'Semiautomático')], max_length=20, verbose_name='Tipo de bloqueo'),
        ),
        migrations.AlterField(
            model_name='usecase',
            name='disabled_reason',
            field=models.TextField(blank=True, default='', help_text='Motivo obligatorio cuando el caso de uso se deshabilita.', verbose_name='Motivo de deshabilitación'),
        ),
        migrations.AlterField(
            model_name='usecase',
            name='last_review_date',
            field=models.DateField(blank=True, null=True, verbose_name='Última revisión'),
        ),
        migrations.AlterField(
            model_name='usecase',
            name='last_validation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Última validación'),
        ),
        migrations.AlterField(
            model_name='usecase',
            name='next_review_date',
            field=models.DateField(blank=True, null=True, verbose_name='Próxima revisión'),
        ),
        migrations.AlterField(
            model_name='usecase',
            name='production_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha puesta en producción'),
        ),
        migrations.AlterField(
            model_name='usecase',
            name='sent_to_ho',
            field=models.CharField(blank=True, choices=[('Sí', 'Sí'), ('No', 'No')], max_length=3, verbose_name='Envío HO'),
        ),
        migrations.AlterField(
            model_name='usecase',
            name='status',
            field=models.CharField(blank=True, choices=[('Test', 'Test'), ('Producción', 'Producción'), ('Desarrollo', 'Desarrollo'), ('Baja', 'Baja'), ('Propuesta', 'Propuesta')], max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='usecase',
            name='validation_result',
            field=models.CharField(choices=[('Nada', 'Nada'), ('OK', 'OK'), ('Advertencia', 'Advertencia'), ('Falló', 'Falló')], default='Nada', max_length=20, verbose_name='Resultado'),
        ),
        migrations.AlterField(
            model_name='usecase',
            name='validation_status',
            field=models.CharField(choices=[('Finalizado', 'Finalizado'), ('En progreso', 'En progreso'), ('No realizado', 'No realizado')], default='No realizado', max_length=20, verbose_name='Estado de validación'),
        ),
    ]
