# Generated by Django 6.0.5 on 2026-06-27 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usecases', '0027_alter_usecase_blocking_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usecase',
            name='full_rule_text',
            field=models.TextField(blank=True, default='', verbose_name='Regla completa'),
        ),
        migrations.AddField(
            model_name='usecase',
            name='functional_description',
            field=models.TextField(blank=True, default='', verbose_name='Descripcion funcional'),
        ),
        migrations.CreateModel(
            name='UseCaseRuleCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=1, verbose_name='Orden')),
                ('condition_type', models.CharField(choices=[('include', 'Incluir'), ('exclude', 'Excluir')], default='include', max_length=12, verbose_name='Tipo')),
                ('field_name', models.CharField(max_length=160, verbose_name='Campo')),
                ('operator', models.CharField(choices=[('equals', 'Es igual a'), ('not_equals', 'No es igual a'), ('contains', 'Contiene'), ('not_contains', 'No contiene'), ('starts_with', 'Empieza con'), ('ends_with', 'Termina con'), ('regex', 'Coincide regex'), ('exists', 'Existe'), ('not_exists', 'No existe'), ('in', 'Esta en lista'), ('not_in', 'No esta en lista')], default='equals', max_length=24, verbose_name='Operador')),
                ('value', models.TextField(blank=True, verbose_name='Valor')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('use_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_conditions', to='usecases.usecase', verbose_name='Caso de uso')),
            ],
            options={
                'verbose_name': 'Condicion de regla',
                'verbose_name_plural': 'Condiciones de regla',
                'ordering': ['position', 'id'],
            },
        ),
    ]
